### ISSUE TITLE
Throwing the error `uninitialized constant Git (NameError)`

### ISSUE THREAD

**Issue by Rajagopalan-M** [rubycoco/git#1]
I have written the following program

```
require 'gitti'

Git.clone( "git@github.com:rubycoco/gitti.git")
```

It throws this error

```
C:\Ruby26\bin\ruby.exe C:/A/GitFolder/first.rb
gitti/0.3.0 on Ruby 2.6.5 (2019-10-01) [i386-mingw32]
Traceback (most recent call last):
C:/A/GitFolder/first.rb:3:in `<main>': uninitialized constant Git (NameError)
Did you mean?  Gitti
```

**Comment by geraldb** [comment]
Thanks for trying gitti and reporting. That is fixed. Please, update the gem to v0.4+. In the old version (before v0.4) you have to include Gitti and in the newer one the Gitti module gets auto-included.

    require 'gitti'

    include Gitti

    Git.clone( "git@github.com:rubycoco/gitti.git")    # or
    Gitti::Git.clone( "git@github.com:rubycoco/gitti.git")

**Comment by Rajagopalan-M** [comment]
yes, it works now. but it throws the following error now

```
C:\Ruby26\bin\ruby.exe C:/A/GitFolder/first.rb
gitti/0.4.0 on Ruby 2.6.5 (2019-10-01) [i386-mingw32]
cmd exec >git clone git@github.com:rubycoco/gitti.git gitti-clone<... FAIL (128)
STDERR:
Cloning into 'gitti-clone'...
Could not create directory '/w//.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
!! ERROR: cmd exec >git clone git@github.com:rubycoco/gitti.git gitti-clone< failed with exit status 128:
Cloning into 'gitti-clone'...
Could not create directory '/w//.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
        2: from C:/A/GitFolder/first.rb:2:in `<main>'
        1: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/gitti-0.4.0/lib/gitti/git.rb:22:in `clone'
C:/Ruby26/lib/ruby/gems/2.6.0/gems/gitti-0.4.0/lib/gitti/git.rb:283:in `run': cmd exec >git clone git@github.com:rubycoco/gitti.git gitti-clone< failed with exit status 128<: Cloning into 'gitti-clone'... (Gitti::GitError)
Could not create directory '/w//.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by geraldb** [comment]
That is a git access / permission ssh error.   You have no write / commit access to the github.com:rubycoco/gitti.git repo.  Fork the repo on github and than retry the clone with the fork.  Cheers. Prost.

**Comment by Rajagopalan-M** [comment]
@geraldb I tried with my folder, it works like a Charm! Thanks!

**Comment by geraldb** [comment]
Great. Sorry for the trouble - still the early days with lots of (unpolished) console output.  Cheers. Prost.

**Comment by Rajagopalan-M** [comment]
> 
> 
> Great. Sorry for the trouble - still the early days with lots of (unpolished) console output. Cheers. Prost.

Sure thanks.
